### ISSUE TITLE
unable to push anything that decreases size of repo

### ISSUE THREAD

**Issue by DmitryFrolovTri** [DmitryFrolovTri/gitea-limit-repo-size#6]
if I push a change that decreases the overall size consumption it should be accepted. 

Current behaviour:
- when I push anything when repository size limit is over such  operation fails

Desired behaviour:
- when I push something that reduces the repostory size it should be accepted

Steps to reproduce:
1) create a repo with a small readme file on disk
make sure that you have pushed the first commit to gitea and its there e.g. `test-repo` into `test-repo` folder
the repo size should be about 26-30K
2) copy the `test-repo` folder into another folder `test-repo1` recursively 
3) inside folder test-repo1 add a bunch of files (e.g. https://github.com/go-gitea/gitea/blob/main/docs/content/doc/administration/config-cheat-sheet.en-us.md) for example 2 times under different name. commit. push
observe size limit change in gitea interface
4) set the limit on `test-repo` in gitea slightly below the displayed repository size in gitea
5) go to the `test-repo` folder (where size of repo is small) and do a:
`git push -f origin main` or `git push -f` - this operation should be successful, because it reduces the repository consumption. 
now such operation fails. 

Some doco on how to reduce size of git repo on disk:
(https://medium.com/@sangeethkumar.tvm.kpm/cleaning-up-a-git-repo-for-reducing-the-repository-size-d11fa496ba48)

**Comment by DmitryFrolovTri** [comment]
@truecode112 here is a boilerplate code that I think works and addresses the issue:

https://github.com/go-gitea/gitea/pull/21820/files#r1198240850

If you like I could push it up and you can continue modifying it to make it better, etc. 
I have a feeling the guys would ask us to move code away from the pre-hook into one of the subprocesses.

**Comment by lunny** [comment]
So you need to know how much size will be increased or reduced before a push merged.

**Comment by DmitryFrolovTri** [comment]
Yes, @lunny exactly - did this as part of the following code:
https://github.com/DmitryFrolovTri/gitea/commit/57c94e63cbb0da55635ef503febe9a06400bc7ea

closing this for now. code "estimates" the size reduction and allows the commit through if reduction is more then addition. So if the repo is over limit and new stuff is attempted to be added it would fail, but if there is some refs that are removed completely and they are not referenced anymore anywhere and there is more size that is freed this way the push would be accepted. So eventually after the few GC and few such changes the repo might go under the size limit and all the pushed would be freely allowed

**Comment by DmitryFrolovTri** [comment]
Yes at least highlevel so I could rely on the git gc to later reduce.
